logging:
    level:
        org:
            hibernate:
                sql: debug
                orm:
                    jdbc:
                        bind: trace


spring:
    jpa:
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                highlight_sql: true

jwt:
    secret: 3601b3ec80fe72be62c3f9ac7e3b8e4ac8aa4dde29a69a7cb1bf973baaad4d21

