logging:
    level:
        org:
            hibernate:
                sql: debug
                orm:
                    jdbc:
                        bind: trace


spring:
    jpa:
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                highlight_sql: true
#                jdbc:
#                    time_zone: UTC
